### Functions

Functions are a convenient way to divide our code into useful blocks of codes, allowing us to order our code, make it more readable, reuse it and save some time. Also functions are a key way to define interfaces so programmers can share their code.


In [63]:
# A function can take inputs, called arguments, and return an output. 
# Though it does not necessarily have to do either of those.

def MyFunction():
    print ("This is my first function")

In [64]:
# Now you can call the function by using its name:

MyFunction()

This is my first function


In [65]:
# Here is a function that takes inputs (arguments) and returns an output

def squared(InputNumber):
    
    return(InputNumber*InputNumber)

In [66]:
squared(10)

100

The examples above are just simple functions for the purpose of education, with just one line of code inside the function, however, functions in reality **can contain blocks of complicated codes**. 

Suppose you create a function that performs an otherwise tedious task that would require hundreds of lines of codes. If you create that function correctly and you are sure that it performs the task flawlessly, then you can share your function! Others can just use your function like a black box! They dont need to know what is inside the function. They can just use it to avoid 'reinventing the wheels'

#### Practice Problem 1

Write a function that would get a number and then print out whether the number is even or odd


In [91]:
def Even_or_Odd(number):
    if number%2 == 0:
        print(number, " is even")
    else:
        print(number, " is odd")

In [93]:
# Test your function on 11 to see whether it says it is odd or even

Even_or_Odd(11)


11  is odd


#### Practice Problem 2

Write a function that would get two numbers and then would return the absolute difference between them

In [95]:
def AbDiff(a,b):
    c = a - b
    if c>= 0:
        print (c)
    else:
        print(-c)

In [100]:
# Test your function on -10 and -12

AbDiff(-10, -12)

2


### Modules, Packages and Libraries

Modules in Python are **Python files** with a **.py** extension. The name of the module will be the name of the file. A Python module can have a set of functions, variables, etc that performs certain tasks. 

To use a module, we would need to **import** the module (since it is in a different file).
A collection of modules is called a **package** and a collection of packages is called a **library**.

For example, **sklearn** is a library. To use sklearn we have to import it:

In [67]:
import sklearn

# We can an alias to shorten our effort each time we need to use that library
import sklearn as sk


In [19]:
# or we can import a specifit function or datasets from the library

from sklearn import datasets

# or we can import everything by using a *
from sklearn import *

Now we can use sklearn library in our program. However each time we want to access a function in that library, we have to reference it:

In [28]:
# for example we want to use a dataset called iris in sklearn's datasets

MyData = datasets.load_iris()

MyData.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

### Data Types - Continuted

We learned about variables, strings, and Lists. There are other types of data. Such as Tuples and Sets and dictionaries: 

### Tuples

We learned that a List is a collection of data points which is ordered and **changeable**. Allows duplicate members. We use **[ ]** to define Lists

A Tuple is a collection which is ordered and **unchangeable**. Allows duplicate members. We use **( )** to define Tuples

In [129]:
# Define a list and a Tuple

MyList = [1, 2, 3]

MyTuple = (1, 2, 3)

In [169]:
# Try to see the difference between the two

MyTuple[0]

1

In [131]:
MyList.append(33)

In [132]:
MyList

[1, 2, 3, 33]

In [170]:
# Try to add a new number to the tuple

MyTuple.append(33)

AttributeError: 'tuple' object has no attribute 'append'

### Dictionaries

A **dictionary** is a data type similar to lists, but works with keys and values instead of indexes. Each value stored in a dictionary can be accessed using a key, which is any type of object (a string, a number, a list, etc.) instead of using its index to address it.

For example, a database of phone numbers could be stored using a dictionary like this:

In [29]:
PhoneBook = {}

# {} shows python to create a dictionary

In [30]:
# To assign items to the dictionary, we do:

PhoneBook["James"] = 9873561315
PhoneBook["Taylor"] = 3655683425
PhoneBook["Mona"] = 8173246785

print(PhoneBook)

{'James': 9873561315, 'Taylor': 3655683425, 'Mona': 8173246785}


We could have instead defined the dictionary like this:

In [31]:
PhoneBook2 = {"James" : 9873561315, "Taylor": 3655683425, "Mona"  : 8173246785}

In [32]:
print(PhoneBook2)

{'James': 9873561315, 'Taylor': 3655683425, 'Mona': 8173246785}


Accessing specific item:

In [33]:
print(PhoneBook["James"])

9873561315


#### Dictionary Keys

Keys are the replacement of indexes for dictionaries. For example, "James", "Taylor", and "Mona" are keys of the above dictionaries. 

Keys have to be unique, meaning you cannot have two different items with the same key

In [34]:
# To see all the keys of a dictionary, use Dictionary_Name.keys()

PhoneBook.keys()

dict_keys(['James', 'Taylor', 'Mona'])

#### Iterating over a dictionary

Dictionaries can be iterated over, just like a list. To iterate over key value pairs, use the following syntax:

In [36]:
for name, number in PhoneBook.items():
    print("%s's Phone Number is %d" % (name, number))
    
# %s and %d tells the print command that name is a string ( s is for string), and number is a digit (d stands for digit)
# So, it prints out name instead of %s and number instead of %d

James's Phone Number is 9873561315
Taylor's Phone Number is 3655683425
Mona's Phone Number is 8173246785


#### Adding and Removing items from a dictionary

In [37]:
# To add:

PhoneBook["Jeff"] = 8192456789

PhoneBook

{'James': 9873561315,
 'Taylor': 3655683425,
 'Mona': 8173246785,
 'Jeff': 8192456789}

In [38]:
# To remove, you can use del or pop

# Using del:

del PhoneBook["Mona"]

In [39]:
PhoneBook

{'James': 9873561315, 'Taylor': 3655683425, 'Jeff': 8192456789}

In [40]:
# Using pop to remove an item from a dictrionary

PhoneBook.pop("James")

9873561315

In [41]:
PhoneBook

{'Taylor': 3655683425, 'Jeff': 8192456789}

#### Practice Problem 3

Define a dictionary with the following keys:Cars, Vacations, Year, and 13

Cars should contain three brands of your choice, Vacation should contain two destinations of your choice, Year should be 2021 and 13 should contain ["Monday", "Tuesday", 15, 23.7] (Does not mean anything, just a bunch of data)
    


In [148]:
Data = {}

Data["Cars"] = ["BMW", "Mercedes", "Tesla"]

Data["Vacations"] = ["Hawaii", "Alaska", "Hawaii"]

Data["Year"] = 2021

Data[13] = ["Monday", "Tuesday", 15, 23.7] 

##### Practice Problem 3.1

In [167]:
# Print out the dictionary

Data

{'Cars': ['BMW', 'Mercedes', 'Tesla'],
 'Vacations': ['Alaska', 'Hawaii'],
 13: ['Monday', 'Tuesday', 15, 23.7]}

##### Practice Problem 3.2

In [155]:
# Remove "Year" from the dictionary

del Data["Year"]

In [158]:
# Print out the dictionary to see the changes

Data


{'Cars': ['BMW', 'Mercedes', 'Tesla'],
 'Vacations': ['Hawaii', 'Alaska', 'Hawaii'],
 13: ['Monday', 'Tuesday', 15, 23.7]}

##### Practice Problem 3.3

In [162]:
# There are two Hawaii in Vacations, remove one of them

Data["Vacations"].remove("Hawaii")

In [163]:
# Print out the dictionary to see the changes

Data

{'Cars': ['BMW', 'Mercedes', 'Tesla'],
 'Vacations': ['Alaska', 'Hawaii'],
 13: ['Monday', 'Tuesday', 15, 23.7]}

##### Practice Problem 3.4

In [165]:
# Use a for loop to print out each car brand one by one

for car in Data["Cars"]:
    print (car)

BMW
Mercedes
Tesla


### Numpy Arrays

**Numpy** is a Python library which stands for Numeric Python. It was created to make computation in Python easier and more efficient (NumPy aims to provide an array object that is up to **50x faster than traditional Python lists**).

**Numpy arrays** are great **alternatives to Python Lists**. Some of the key advantages of Numpy arrays are that they are fast, easy to work with, and give users the opportunity to perform calculations across entire arrays.

In [82]:
# We can make an array out of a list 

MyList = [1, 2, 3, 4, 5, 6]

import numpy as np

MyArray = np.array(MyList)

In [83]:
MyArray

array([1, 2, 3, 4, 5, 6])

To access a specific number in an array, we can use its index similar to lists 

In [84]:
print (MyArray[0])

1


We can also make an array out of a Tuple:

In [174]:
# Make a Numpy array with MyTuple

MyArray = np.array(MyTuple)

Multi dimension arrays

In [176]:
# So far, we have had one dimensional (1D) arrays. We can have 2D (also called matrices) and 3D arrays too
# A 3D arrays is an array that has 2D arrays (matrices) as its elements

# An array with a single item is called 0 dimensional

MyArray2 = np.array([[1, 2, 3], [4, 5, 6]])
MyArray3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [180]:
# Print out the arrays to see them

MyArray2

array([[1, 2, 3],
       [4, 5, 6]])

**ndim** would return the dimension of an array

In [187]:
# Print out the dimension of MyArray, MyArray2, and MyArray3

print("MyArray Dimension is", MyArray.ndim)
print("MyArray2 Dimension is", MyArray2.ndim)
print("MyArray3 Dimension is", MyArray3.ndim)

MyArray Dimension is 1
MyArray2 Dimension is 2
MyArray3 Dimension is 3


**Shape** of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [209]:
# Lets see the shape of MyArray, MyArray2 and MyArray3

print("Shape of MyArray = ", MyArray.shape)
print("Shape of MyArray2 = ", MyArray2.shape)
print("Shape of MyArray3 = ", MyArray3.shape)


Shape of MyArray =  (5,)
Shape of MyArray2 =  (2, 3)
Shape of MyArray3 =  (2, 2, 3)


**Accessing elements** of Arrays

In [192]:
# Print out the 2nd element of the first dimension of MyArray2

print(MyArray2[0,1])

2


In [196]:
# Print out the last element of the second dimension of MyArray2

print(MyArray2[1,-1])



6


In [221]:
# Accessing elements of a multi dimensional array one by one 
# We can do this via a for loop

for x in MyArray2:
    # x is a 1D array
    for y in x:
        print (y)

1
2
3
4
5
6


#### Slicing Arrays


In [199]:
# Given the following array:
Digit = np.array(range(10))

# Make a slice that contains the third element upto the 6th element (including 6th)
SubDigit = Digit[2:7]



SubDigit

array([3, 4, 5, 6])

#### Copying an array

In [202]:
# Lets make a copy of MyArray

CopyArray = MyArray.copy()

# Now see the content of the copy

CopyArray

array([1, 2, 3, 4])